//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.web.zhutong.cn.com/", ConfigurationName="ServiceReference1.SendsmsWebService")]
    public interface SendsmsWebService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Common.ServiceReference1.getBalanceApiResponse getBalanceApi(Common.ServiceReference1.getBalanceApi request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Common.ServiceReference1.sendSmsResponse sendSms(Common.ServiceReference1.sendSms request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Common.ServiceReference1.getBatchReportResponse getBatchReport(Common.ServiceReference1.getBatchReport request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Common.ServiceReference1.getSubmitStatisticsResponse getSubmitStatistics(Common.ServiceReference1.getSubmitStatistics request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Common.ServiceReference1.getReplyDataResponse getReplyData(Common.ServiceReference1.getReplyData request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Common.ServiceReference1.sendChangeSmsResponse sendChangeSms(Common.ServiceReference1.sendChangeSms request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceApi {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBalanceApi", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getBalanceApiBody Body;
        
        public getBalanceApi() {
        }
        
        public getBalanceApi(Common.ServiceReference1.getBalanceApiBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBalanceApiBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public getBalanceApiBody() {
        }
        
        public getBalanceApiBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceApiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBalanceApiResponse", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getBalanceApiResponseBody Body;
        
        public getBalanceApiResponse() {
        }
        
        public getBalanceApiResponse(Common.ServiceReference1.getBalanceApiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBalanceApiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getBalanceApiResponseBody() {
        }
        
        public getBalanceApiResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSms {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSms", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.sendSmsBody Body;
        
        public sendSms() {
        }
        
        public sendSms(Common.ServiceReference1.sendSmsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendSmsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string arg7;
        
        public sendSmsBody() {
        }
        
        public sendSmsBody(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSmsResponse", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.sendSmsResponseBody Body;
        
        public sendSmsResponse() {
        }
        
        public sendSmsResponse(Common.ServiceReference1.sendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendSmsResponseBody() {
        }
        
        public sendSmsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBatchReport {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBatchReport", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getBatchReportBody Body;
        
        public getBatchReport() {
        }
        
        public getBatchReport(Common.ServiceReference1.getBatchReportBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBatchReportBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getBatchReportBody() {
        }
        
        public getBatchReportBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBatchReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBatchReportResponse", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getBatchReportResponseBody Body;
        
        public getBatchReportResponse() {
        }
        
        public getBatchReportResponse(Common.ServiceReference1.getBatchReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBatchReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getBatchReportResponseBody() {
        }
        
        public getBatchReportResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubmitStatistics {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubmitStatistics", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getSubmitStatisticsBody Body;
        
        public getSubmitStatistics() {
        }
        
        public getSubmitStatistics(Common.ServiceReference1.getSubmitStatisticsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getSubmitStatisticsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public getSubmitStatisticsBody() {
        }
        
        public getSubmitStatisticsBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubmitStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubmitStatisticsResponse", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getSubmitStatisticsResponseBody Body;
        
        public getSubmitStatisticsResponse() {
        }
        
        public getSubmitStatisticsResponse(Common.ServiceReference1.getSubmitStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getSubmitStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getSubmitStatisticsResponseBody() {
        }
        
        public getSubmitStatisticsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReplyData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReplyData", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getReplyDataBody Body;
        
        public getReplyData() {
        }
        
        public getReplyData(Common.ServiceReference1.getReplyDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getReplyDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public getReplyDataBody() {
        }
        
        public getReplyDataBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReplyDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReplyDataResponse", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.getReplyDataResponseBody Body;
        
        public getReplyDataResponse() {
        }
        
        public getReplyDataResponse(Common.ServiceReference1.getReplyDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getReplyDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getReplyDataResponseBody() {
        }
        
        public getReplyDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendChangeSms {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendChangeSms", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.sendChangeSmsBody Body;
        
        public sendChangeSms() {
        }
        
        public sendChangeSms(Common.ServiceReference1.sendChangeSmsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendChangeSmsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        public sendChangeSmsBody() {
        }
        
        public sendChangeSmsBody(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendChangeSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendChangeSmsResponse", Namespace="http://webservice.web.zhutong.cn.com/", Order=0)]
        public Common.ServiceReference1.sendChangeSmsResponseBody Body;
        
        public sendChangeSmsResponse() {
        }
        
        public sendChangeSmsResponse(Common.ServiceReference1.sendChangeSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendChangeSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendChangeSmsResponseBody() {
        }
        
        public sendChangeSmsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendsmsWebServiceChannel : Common.ServiceReference1.SendsmsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendsmsWebServiceClient : System.ServiceModel.ClientBase<Common.ServiceReference1.SendsmsWebService>, Common.ServiceReference1.SendsmsWebService {
        
        public SendsmsWebServiceClient() {
        }
        
        public SendsmsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendsmsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendsmsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendsmsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ServiceReference1.getBalanceApiResponse Common.ServiceReference1.SendsmsWebService.getBalanceApi(Common.ServiceReference1.getBalanceApi request) {
            return base.Channel.getBalanceApi(request);
        }
        
        public string getBalanceApi(string arg0, string arg1, string arg2) {
            Common.ServiceReference1.getBalanceApi inValue = new Common.ServiceReference1.getBalanceApi();
            inValue.Body = new Common.ServiceReference1.getBalanceApiBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            Common.ServiceReference1.getBalanceApiResponse retVal = ((Common.ServiceReference1.SendsmsWebService)(this)).getBalanceApi(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ServiceReference1.sendSmsResponse Common.ServiceReference1.SendsmsWebService.sendSms(Common.ServiceReference1.sendSms request) {
            return base.Channel.sendSms(request);
        }
        
        public string sendSms(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7) {
            Common.ServiceReference1.sendSms inValue = new Common.ServiceReference1.sendSms();
            inValue.Body = new Common.ServiceReference1.sendSmsBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            Common.ServiceReference1.sendSmsResponse retVal = ((Common.ServiceReference1.SendsmsWebService)(this)).sendSms(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ServiceReference1.getBatchReportResponse Common.ServiceReference1.SendsmsWebService.getBatchReport(Common.ServiceReference1.getBatchReport request) {
            return base.Channel.getBatchReport(request);
        }
        
        public string getBatchReport(string arg0, string arg1) {
            Common.ServiceReference1.getBatchReport inValue = new Common.ServiceReference1.getBatchReport();
            inValue.Body = new Common.ServiceReference1.getBatchReportBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Common.ServiceReference1.getBatchReportResponse retVal = ((Common.ServiceReference1.SendsmsWebService)(this)).getBatchReport(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ServiceReference1.getSubmitStatisticsResponse Common.ServiceReference1.SendsmsWebService.getSubmitStatistics(Common.ServiceReference1.getSubmitStatistics request) {
            return base.Channel.getSubmitStatistics(request);
        }
        
        public string getSubmitStatistics(string arg0, string arg1, string arg2) {
            Common.ServiceReference1.getSubmitStatistics inValue = new Common.ServiceReference1.getSubmitStatistics();
            inValue.Body = new Common.ServiceReference1.getSubmitStatisticsBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            Common.ServiceReference1.getSubmitStatisticsResponse retVal = ((Common.ServiceReference1.SendsmsWebService)(this)).getSubmitStatistics(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ServiceReference1.getReplyDataResponse Common.ServiceReference1.SendsmsWebService.getReplyData(Common.ServiceReference1.getReplyData request) {
            return base.Channel.getReplyData(request);
        }
        
        public string getReplyData(string arg0, string arg1) {
            Common.ServiceReference1.getReplyData inValue = new Common.ServiceReference1.getReplyData();
            inValue.Body = new Common.ServiceReference1.getReplyDataBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Common.ServiceReference1.getReplyDataResponse retVal = ((Common.ServiceReference1.SendsmsWebService)(this)).getReplyData(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.ServiceReference1.sendChangeSmsResponse Common.ServiceReference1.SendsmsWebService.sendChangeSms(Common.ServiceReference1.sendChangeSms request) {
            return base.Channel.sendChangeSms(request);
        }
        
        public string sendChangeSms(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            Common.ServiceReference1.sendChangeSms inValue = new Common.ServiceReference1.sendChangeSms();
            inValue.Body = new Common.ServiceReference1.sendChangeSmsBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            Common.ServiceReference1.sendChangeSmsResponse retVal = ((Common.ServiceReference1.SendsmsWebService)(this)).sendChangeSms(inValue);
            return retVal.Body.@return;
        }
    }
}
